### ISSUE TITLE
Design inspiration

### ISSUE THREAD

**Issue by sayanee** [sauvc/2018#1]
## Websites

1. [WWDC](https://developer.apple.com/wwdc)
1. [Google IO](https://events.google.com/io)
1. [CSS Conf](http://2017.cssconf.eu)
1. [CSS Conf China](http://2016.jsconf.cn)
1. [JS Conf Belgium](https://www.jsconf.be/en)
1. [JS Conf Australia](http://2016.jsconfau.com)
1. [Redis Conf](http://redisconf.com)
1. [JS Conf Argentina](https://www.jsconfar.com)
1. [&yet](http://andyetconf.com)

## Effects

1. [form fields](https://tympanus.net/Development/TextInputEffects/)

## Design elements

1. One page website
1. Anchor links to sections
1. Section on 6 pointers on what to expect
1. full width images
1. Agenda / Schedule
1. Map of venue
1. Section on people with profile pictures
1. Key numbers on years, participants, countries, etc
1. sponsors

**Comment by notthetup** [comment]
Current website uses https://fonts.google.com/specimen/Audiowide as font

![screenshot 2017-04-23 19 05 54](https://cloud.githubusercontent.com/assets/553140/25313069/a886b7f4-2859-11e7-8f78-43fe59565632.jpg)

**Comment by notthetup** [comment]
# Website layout

## Navigation bar

![image](https://user-images.githubusercontent.com/413879/28750991-e4671166-752e-11e7-84b4-c3b6a9c5c9dd.png)

## Hero

![image](https://user-images.githubusercontent.com/413879/28751220-97fc2572-7534-11e7-993d-6f9adbd62ac8.png)

![screenshot 2017-04-23 19 13 37](https://cloud.githubusercontent.com/assets/553140/25313040/5703d010-2859-11e7-9627-a940d129169f.jpg)

## Information

Why attend?

![screenshot 2017-04-23 19 12 54](https://cloud.githubusercontent.com/assets/553140/25313054/823bcd46-2859-11e7-9967-05d2f3e89be8.jpg)

![screenshot 2017-04-23 19 12 44](https://cloud.githubusercontent.com/assets/553140/25313062/9b49d1a2-2859-11e7-86e5-8e98f8d18cb1.jpg)

![screenshot 2017-04-23 19 12 20](https://cloud.githubusercontent.com/assets/553140/25313057/8b223d82-2859-11e7-9e77-848f31472c0b.jpg)

![screenshot 2017-04-23 19 13 09](https://cloud.githubusercontent.com/assets/553140/25313052/7d80beb0-2859-11e7-973d-3cba9bd2c7f2.jpg)


## People involved

![screenshot 2017-04-23 19 12 59](https://cloud.githubusercontent.com/assets/553140/25313041/5b680a40-2859-11e7-9c22-1184748569df.jpg)

## Sponsors

![screenshot 2017-04-23 19 13 28](https://cloud.githubusercontent.com/assets/553140/25313044/61da8484-2859-11e7-9471-0b78378a38ca.jpg)
 

## Agenda

![screenshot 2017-04-23 19 13 57](https://cloud.githubusercontent.com/assets/553140/25313036/4833fbc8-2859-11e7-9c43-1162279e1e23.jpg)


## Location, Maps and Directions

![screenshot 2017-04-23 19 14 30](https://cloud.githubusercontent.com/assets/553140/25313027/3c9a5370-2859-11e7-8790-5c70b09b6843.jpg)

![screenshot 2017-04-23 19 12 01](https://cloud.githubusercontent.com/assets/553140/25313026/34fbf146-2859-11e7-8b64-c87e6c1e0aa8.jpg)

![screenshot 2017-04-23 19 13 18](https://cloud.githubusercontent.com/assets/553140/25313048/6a33c92e-2859-11e7-988c-61b9e356c05e.jpg)

**Comment by notthetup** [comment]
One idea of base color #166CA3

http://paletton.com/#uid=43v0u0ktqv+iiFwnwzywwq7ADkA

**Comment by notthetup** [comment]
We also need a logo for SAUVC.

**Comment by sayanee** [comment]
Checkout the dynamic water level for the footer: https://dribbble.com/shots/2604875-The-Submarine-Creative-Showreel

![untitled-1](https://cloud.githubusercontent.com/assets/413879/25314709/854a9cd4-287b-11e7-95a9-d61c9b7dea18.gif)

**Comment by notthetup** [comment]
Water wave effect.

https://codepen.io/tedmcdo/pen/PqxKXg

**Comment by sayanee** [comment]
https://dribbble.com/shots/2779465-Ella-Ollie-s

**Comment by notthetup** [comment]
https://codepen.io/ajerez/pen/EaEEOW

https://codepen.io/anon/pen/brEYmy


https://dribbble.com/shots/3603155-Ahoy
