### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by DonaBanerjee** [sauvc/2018#30]
Design suggestions:

- "Explore the wonders..." change that into one line, with no bold text, no highlights and smaller font so that emphasis is on the rest of the main page.
- Move propelling logo to "Welcome to SAUVC 2018 Singapore, March 9-12" 
- Add more space above and below "Welcome to SAUVC 2018 Singapore, March 9-12" 
- Social media and platform links to be visible in the front page without scrolling hopefully. If not, move that to the "About section" as it has no links to it on its own unlike all the other sections.

**Comment by sayanee** [comment]
Thanks @DonaBanerjee - closing after discussing with the team that this is not required 🙇‍♀️
