### ISSUE TITLE
UX/UI

### ISSUE THREAD

**Issue by DonaBanerjee** [sauvc/2018#31]
UX/UI suggestins:

1. Move Venue to be first in line after Main page (as most people would need to know location when knowing date to lock that into their calendars easily.)

2. Remove: "Registered Teams" button as it is not a strong call to action. Move that up to menu line instead.

3. Information needs a title in the section labelled "Information" to be consistent with other sections.
Left align all text and use one colour for the titles "Purpose" "Mentorship etc."

Reduce font in menu line if there is no space OR reduce sections (e.g. The "Contact Us" section can go under the "About" section.)

4. All links goes to correct sections but need to capture the title as well to avoid confusion.
E.g. Clicking on Contact Us shows "About" as a title as the first thing you'd see. "Contact us" can be seen on landing instead of by scrolling up = no confusion. :)

Loving the logo propelling by and the bubbles and sound OMG!

**Comment by sayanee** [comment]
Thanks @DonaBanerjee - closing after discussing with the team that this is not required 🙇‍♀️
