### ISSUE TITLE
Add a section on Multimedia

### ISSUE THREAD

**Issue by notthetup** [sauvc/2018#7]
Multimedia section can contain

- A flickr gallery of photos form previous competition (https://www.flickr.com/photos/sauvc/)
- A Youtube player of videos from previous competition (https://www.youtube.com/user/ARLTMSINUSChannel)

**Comment by sayanee** [comment]
done with section after the hero:

![image](https://user-images.githubusercontent.com/413879/29747737-69ebcc7e-8b36-11e7-9c49-235fe87468b4.png)
