### ISSUE TITLE
Add a footer

### ISSUE THREAD

**Issue by notthetup** [sauvc/2018#9]
Footer can have

- IEEE Logo and a mention that SAUVC is organised by IEEE OES Singapore.
- Links to various social media accounts for SAUVC
  - Facebook (https://www.facebook.com/SingaporeAUVChallenge/) 
  - Twitter (https://twitter.com/ieeeoessg)
  - Reddit (https://www.reddit.com/r/SAUVC/)

**Comment by sayanee** [comment]
Moved social links to after hero

![image](https://user-images.githubusercontent.com/413879/29747634-651310c0-8b33-11e7-9f6e-e375f7024f43.png)

**Comment by sayanee** [comment]
![image](https://user-images.githubusercontent.com/413879/29747926-839d010a-8b3c-11e7-8a82-3ff02ce18c65.png)
